name: iOS Simulator Test

permissions:
  contents: read

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ios_simulator_test:
    runs-on: macos-latest
    strategy:
      matrix:
        ios_version: ['18.5', '26.0']
      fail-fast: false
    
    steps:
    - uses: actions/checkout@v4

    - name: Launch simulator first
      run: |
        xcrun simctl list runtimes
        xcodebuild -runFirstLaunch

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod

    - name: Build mobilecli
      run: |
        make

    - name: Run tests for iOS ${{ matrix.ios_version }}
      run: |
        cd test
        npm install
        npm run test -- --grep "iOS ${{ matrix.ios_version }}"
