name: iOS Simulator Test

permissions:
  contents: read

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ios_simulator_test:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod

    - name: Build mobilecli
      run: |
        go build -o mobilecli

    - name: List available iOS simulators
      run: |
        xcrun simctl list devices available

    - name: Create iOS 18 simulator
      run: |
        RUNTIME=$( xcrun simctl list runtimes | grep "iOS 18." | head -1 | awk '{print $NF}' )
        xcrun simctl create "iPhone-15-iOS-18" "iPhone 15" "$RUNTIME"

    - name: Boot iOS 18 simulator
      run: |
        DEVICE_ID=$(xcrun simctl list devices | grep "iPhone-15-iOS-18" | grep -E -o -i "([0-9a-f]{8}-([0-9a-f]{4}-){3}[0-9a-f]{12})")
        xcrun simctl boot "$DEVICE_ID"
        xcrun simctl bootstatus "$DEVICE_ID"

    - name: Wait for simulator to be ready
      run: |
        sleep 30

    - name: Run mobilecli devices
      run: |
        ./mobilecli devices

    - name: Shutdown simulator
      if: always()
      run: |
        DEVICE_ID=$(xcrun simctl list devices | grep "iPhone-15-iOS-18" | grep -E -o -i "([0-9a-f]{8}-([0-9a-f]{4}-){3}[0-9a-f]{12})")
        xcrun simctl shutdown "$DEVICE_ID" || true
        xcrun simctl delete "$DEVICE_ID" || true
