name: iOS Simulator Test

permissions:
  contents: read

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ios_simulator_test_18_26:
    runs-on: macos-latest
    strategy:
      matrix:
        ios_version: ['18', '26']
      fail-fast: false
    
    steps:
    - uses: actions/checkout@v4

    - name: Launch simulator first
      run: |
        xcrun simctl list runtimes
        xcodebuild -runFirstLaunch

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod

    - name: Build mobilecli
      run: |
        make

    - name: Run tests for iOS ${{ matrix.ios_version }}
      run: |
        cd test
        npm install
        npm run test -- --grep "iOS ${{ matrix.ios_version }}"

  ios_simulator_test_17:
    runs-on: macos-14
    strategy:
      matrix:
        ios_version: ['17']
      fail-fast: false
    
    steps:
    - uses: actions/checkout@v4

    - name: Launch simulator first
      run: |
        xcrun simctl list runtimes
        xcodebuild -runFirstLaunch

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod

    - name: Build mobilecli
      run: |
        make

    - name: Run tests for iOS ${{ matrix.ios_version }}
      run: |
        cd test
        npm install
        npm run test -- --grep "iOS ${{ matrix.ios_version }}"

  ios_simulator_test_16:
    runs-on: macos-13
    strategy:
      matrix:
        ios_version: ['16']
      fail-fast: false
    
    steps:
    - uses: actions/checkout@v4

    - name: Launch simulator first
      run: |
        xcrun simctl list runtimes
        xcodebuild -runFirstLaunch

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod

    - name: Build mobilecli
      run: |
        make

    - name: Run tests for iOS ${{ matrix.ios_version }}
      run: |
        cd test
        npm install
        npm run test -- --grep "iOS ${{ matrix.ios_version }}"
